### ISSUE TITLE
Stuck?

### ISSUE THREAD

**Issue by Mekkiepoo** [johnovelli/anya-shop-bot#2]
Very often after checking the claws, it hangs indefinitely until you manually move.  Seems to only do 1-2 successful loops before this happens.

**Comment by johnovelli** [comment]
Hi @Mekkiepoo , how u doing ?
Thks for the reply, can u explain me more about your issue ?
The bot works for certain time and stucks or stucks in the beginning of the process ?
Ill try to make some changes and release a new version.
Just need to know more about the issue if u could.

**Comment by Mekkiepoo** [comment]
It's not even for a certain time.. I don't know if it's a setting i've
gotten wrong or what, but the character will talk to anya, mouse over
things, then just hang there.  Sometimes it will loop once or twice, but it
always stops very quickly.  When i click on the portal, it will go do
another loop and then stop again.   I will take a video to show you as soon
as i can.

**Comment by Mekkiepoo** [comment]
Here is a video of the issue... apologies for the open mic, i didnt realize
the webcam mic was active.
 Untitled.mp4
<https://drive.google.com/file/d/1-P9r8nHHFiT86re_73RLmq5hEguBHalS/view?usp=drive_web>

**Comment by johnovelli** [comment]
Hey @Mekkiepoo , first off all, thanks for helping me, I think I know the issue and I fixing it, however, if you continue to help me I will be very grateful. This is the first bot that I have developed and I needed help like the one you are giving me I will make a new release and send it to you by tomorrow but if you can continue to help me I will be very grateful. Thank you very much and consider unlock your python powers too !! 😃

**Comment by johnovelli** [comment]
Hey @Mekkiepoo , I need permission to open the link, first off all thanks for helping me, I think I know the issue and I fixing it, however, if you continue to help me I will be very grateful. This is the first bot that I have developed and I needed help like the one you are giving me I will make a new release and send it to you by tomorrow but if you can continue to help me I will be very grateful. Thank you very much and consider unlock your python powers too !! 😃

**Comment by Mekkiepoo** [comment]
Oh sorry about that, didn't realize it needed permissions... let me fix
that ^^

**Comment by johnovelli** [comment]
@Mekkiepoo sorry taking to long, I think the issue that was ocorring in your pc is fixed.
This is the latest release:
https://github.com/johnovelli/anya-shop-bot/releases/tag/v0.1.2
Please let me know if it fixed for you ? :D
Obs: don`t forget to set the config again.

**Comment by Mekkiepoo** [comment]
Works like a charm now, good job :)

**Comment by johnovelli** [comment]
@Mekkiepoo heey!! thks maan!!! I Very happy here !
Can I mention you in the tag of the new version ?
Pointing out that you helped me (:

**Comment by Mekkiepoo** [comment]
Ehmm all i did was report a bug lol xD
